/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/health/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness */
    get: operations["liveness_api_v1_health_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness */
    get: operations["readiness_api_v1_health_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Projects
     * @description Newest first by default; `q` matches name or description.
     */
    get: operations["list_projects_api_v1_projects_get"];
    put?: never;
    /** Create Project */
    post: operations["create_project_api_v1_projects_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{project_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Project */
    get: operations["get_project_api_v1_projects__project_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/projects/{project_id}/scans": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Create Scan
     * @description Queue a scan of a named npm package version or GitHub commit; the server builds the URL.
     */
    post: operations["create_scan_api_v1_projects__project_id__scans_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/scans/{scan_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Scan
     * @description Status with timestamps, tool runs and the number of units per priority.
     */
    get: operations["get_scan_api_v1_scans__scan_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/scans/{scan_id}/units": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Units
     * @description Location units in queue order (P1, P2, U, P3, P4, then unit_key).
     */
    get: operations["list_units_api_v1_scans__scan_id__units_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/scans/{scan_id}/units/{unit_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Unit
     * @description Evidence record, reason, policy provenance and the raw findings of one unit.
     */
    get: operations["get_unit_api_v1_scans__scan_id__units__unit_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * ErrorResponse
     * @description Body of every error response; matches FastAPI's own HTTPException shape.
     */
    ErrorResponse: {
      /** Detail */
      detail: string;
    };
    /** FindingRead */
    FindingRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Tool */
      tool: string;
      /** Language */
      language: string;
      /** Raw Id */
      raw_id: string | null;
      /** Rule Id */
      rule_id: string;
      /** Raw Rule Id */
      raw_rule_id: string | null;
      /** File Path */
      file_path: string | null;
      /** Start Line */
      start_line: number | null;
      /** End Line */
      end_line: number | null;
      /** Start Column */
      start_column: number | null;
      /** End Column */
      end_column: number | null;
      /** Message */
      message: string;
      /** Cwe Ids */
      cwe_ids: string[];
      /** Raw Result */
      raw_result: {
        [key: string]: unknown;
      };
    };
    /** GitHubSource */
    GitHubSource: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "github";
      /** Owner */
      owner: string;
      /** Repo */
      repo: string;
      /**
       * Commit
       * @description Full commit SHA-1
       */
      commit: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** Liveness */
    Liveness: {
      /**
       * Status
       * @default ok
       * @constant
       */
      status: "ok";
    };
    /** NpmSource */
    NpmSource: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      kind: "npm";
      /**
       * Package
       * @example curling
       */
      package: string;
      /**
       * Version
       * @description Exact SemVer version
       * @example 0.2.0
       */
      version: string;
    };
    /** ProjectCreate */
    ProjectCreate: {
      /** Name */
      name: string;
      /** Description */
      description?: string | null;
    };
    /**
     * ProjectPage
     * @description One page of projects.
     */
    ProjectPage: {
      /** Items */
      items: components["schemas"]["ProjectRead"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** ProjectRead */
    ProjectRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
    };
    /** Readiness */
    Readiness: {
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "degraded";
      checks: components["schemas"]["ReadinessChecks"];
    };
    /** ReadinessChecks */
    ReadinessChecks: {
      /**
       * Postgres
       * @enum {string}
       */
      postgres: "ok" | "unavailable";
      /**
       * Redis
       * @enum {string}
       */
      redis: "ok" | "unavailable";
      /**
       * Storage
       * @enum {string}
       */
      storage: "ok" | "unavailable";
    };
    /** ScanAccepted */
    ScanAccepted: {
      /**
       * Scan Id
       * Format: uuid
       */
      scan_id: string;
      /**
       * Snapshot Id
       * Format: uuid
       */
      snapshot_id: string;
      /** Status */
      status: string;
    };
    /** ScanCreate */
    ScanCreate: {
      /** Source */
      source:
        | components["schemas"]["NpmSource"]
        | components["schemas"]["GitHubSource"];
      /**
       * Profile
       * @default command-injection-v0.1
       * @constant
       */
      profile: "command-injection-v0.1";
    };
    /** ScanRead */
    ScanRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Project Id
       * Format: uuid
       */
      project_id: string;
      /** Status */
      status: string;
      /** Profile */
      profile: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Started At */
      started_at: string | null;
      /** Finished At */
      finished_at: string | null;
      /** Error Message */
      error_message: string | null;
      /** Reconciler Version */
      reconciler_version: string | null;
      /** Policy Version */
      policy_version: string | null;
      snapshot: components["schemas"]["SnapshotRead"];
      /** Tool Runs */
      tool_runs: components["schemas"]["ToolRunRead"][];
      /** Unit Counts */
      unit_counts: {
        [key: string]: number;
      };
    };
    /** SnapshotRead */
    SnapshotRead: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Status */
      status: string;
      /** Source Kind */
      source_kind: string | null;
      /** Source Coordinate */
      source_coordinate: string | null;
      /** Sha256 */
      sha256: string | null;
      /** Provenance Kind */
      provenance_kind: string | null;
      /** Error Message */
      error_message: string | null;
    };
    /** ToolRunRead */
    ToolRunRead: {
      /** Tool */
      tool: string;
      /** Language */
      language: string;
      /** Status */
      status: string;
      /** Tool Version */
      tool_version: string | null;
      /** Exit Code */
      exit_code: number | null;
      /** Error Message */
      error_message: string | null;
    };
    /** UnitDetail */
    UnitDetail: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Unit Key
       * @description Canonical unit ID, comparable with the experiment CLI
       */
      unit_key: string;
      /** Path */
      path: string | null;
      /** Start Line */
      start_line: number | null;
      /** End Line */
      end_line: number | null;
      /** Start Column */
      start_column: number | null;
      /** End Column */
      end_column: number | null;
      /** Sink Kind */
      sink_kind: string | null;
      /** Argument Role */
      argument_role: string | null;
      /** Mapping Status */
      mapping_status: string;
      /**
       * Priority
       * @enum {string}
       */
      priority: "P1" | "P2" | "U" | "P3" | "P4";
      /** Decision Id */
      decision_id: string;
      /** Reason */
      reason: string;
      /** Tools */
      tools: string[];
      /** Matched Conditions */
      matched_conditions: string[];
      /** Predicate Values */
      predicate_values: {
        [key: string]: boolean;
      };
      /** Unknown Fields */
      unknown_fields: string[];
      /** Source Types */
      source_types: string[];
      /** Shell State */
      shell_state: string | null;
      /** Blocker Proof */
      blocker_proof: {
        [key: string]: unknown;
      } | null;
      /** Finding Evidence */
      finding_evidence: {
        [key: string]: unknown;
      }[];
      /** Policy Id */
      policy_id: string;
      /** Policy Version */
      policy_version: string;
      /** Policy Sha256 */
      policy_sha256: string;
      /** Spec Sha256 */
      spec_sha256: string;
      /** Rule Claims Version */
      rule_claims_version: string;
      /** Rule Claims Sha256 */
      rule_claims_sha256: string;
      /** Reconciler Version */
      reconciler_version: string;
      /** Findings */
      findings: components["schemas"]["FindingRead"][];
    };
    /**
     * UnitPage
     * @description One page of a scan's location units in queue order.
     */
    UnitPage: {
      /** Items */
      items: components["schemas"]["UnitSummary"][];
      /** Total */
      total: number;
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
    };
    /** UnitSummary */
    UnitSummary: {
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Unit Key
       * @description Canonical unit ID, comparable with the experiment CLI
       */
      unit_key: string;
      /** Path */
      path: string | null;
      /** Start Line */
      start_line: number | null;
      /** End Line */
      end_line: number | null;
      /** Start Column */
      start_column: number | null;
      /** End Column */
      end_column: number | null;
      /** Sink Kind */
      sink_kind: string | null;
      /** Argument Role */
      argument_role: string | null;
      /** Mapping Status */
      mapping_status: string;
      /**
       * Priority
       * @enum {string}
       */
      priority: "P1" | "P2" | "U" | "P3" | "P4";
      /** Decision Id */
      decision_id: string;
      /** Reason */
      reason: string;
      /** Tools */
      tools: string[];
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  liveness_api_v1_health_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Liveness"];
        };
      };
    };
  };
  readiness_api_v1_health_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Readiness"];
        };
      };
      /** @description A dependency is unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Readiness"];
        };
      };
    };
  };
  list_projects_api_v1_projects_get: {
    parameters: {
      query?: {
        /** @description Case-insensitive substring match */
        q?: string | null;
        /** @description Maximum number of items to return */
        limit?: number;
        /** @description Number of items to skip */
        offset?: number;
        /** @description Sort field, prefixed with '-' for descending. One of: created_at, name. Default: -created_at. */
        sort?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectPage"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_project_api_v1_projects_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ProjectCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectRead"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_project_api_v1_projects__project_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProjectRead"];
        };
      };
      /** @description Project not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_scan_api_v1_projects__project_id__scans_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        project_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ScanCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScanAccepted"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_scan_api_v1_scans__scan_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        scan_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ScanRead"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  list_units_api_v1_scans__scan_id__units_get: {
    parameters: {
      query?: {
        tier?: ("P1" | "P2" | "U" | "P3" | "P4") | null;
        tool?: ("semgrep" | "codeql") | null;
        /** @description Maximum number of items to return */
        limit?: number;
        /** @description Number of items to skip */
        offset?: number;
      };
      header?: never;
      path: {
        scan_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitPage"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_unit_api_v1_scans__scan_id__units__unit_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        unit_id: string;
        scan_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitDetail"];
        };
      };
      /** @description Not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
