"""Initial project, snapshot, scan, tool run, and finding tables."""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "projects",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_snapshots",
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.Column("bucket", sa.String(length=255), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("file_count", sa.Integer(), nullable=True),
        sa.Column("manifest_key", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('uploading', 'validating', 'ready', 'failed')", name="ck_snapshot_status"
        ),
        sa.CheckConstraint("file_count >= 0", name="ck_snapshot_file_count"),
        sa.CheckConstraint("size_bytes >= 0", name="ck_snapshot_size"),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_source_snapshots_project_id"), "source_snapshots", ["project_id"], unique=False
    )
    op.create_table(
        "scans",
        sa.Column("snapshot_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'partial', 'failed', 'cancelled')",
            name="ck_scan_status",
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["source_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scans_snapshot_id"), "scans", ["snapshot_id"], unique=False)
    op.create_table(
        "tool_runs",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("tool", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("tool_version", sa.String(length=80), nullable=True),
        sa.Column(
            "config",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("result_key", sa.Text(), nullable=True),
        sa.Column("log_key", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'partial', 'failed', 'cancelled')",
            name="ck_tool_run_status",
        ),
        sa.CheckConstraint("attempt > 0", name="ck_tool_run_attempt"),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scan_id", "tool", "language", "attempt", name="uq_tool_run_attempt"),
    )
    op.create_index(op.f("ix_tool_runs_scan_id"), "tool_runs", ["scan_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("tool_run_id", sa.Uuid(), nullable=False),
        sa.Column("result_index", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Text(), nullable=False),
        sa.Column("file_path", sa.Text(), nullable=True),
        sa.Column("start_line", sa.Integer(), nullable=True),
        sa.Column("end_line", sa.Integer(), nullable=True),
        sa.Column("start_column", sa.Integer(), nullable=True),
        sa.Column("end_column", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=True),
        sa.Column(
            "cwe_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("rule_help_url", sa.Text(), nullable=True),
        sa.Column("classification_source", sa.String(length=32), nullable=True),
        sa.Column("mapping_version", sa.String(length=80), nullable=True),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("end_column >= 1", name="ck_finding_end_column"),
        sa.CheckConstraint("end_line >= start_line", name="ck_finding_end_line"),
        sa.CheckConstraint("result_index >= 0", name="ck_finding_result_index"),
        sa.CheckConstraint("start_column >= 1", name="ck_finding_start_column"),
        sa.CheckConstraint("start_line >= 1", name="ck_finding_start_line"),
        sa.ForeignKeyConstraint(
            ["tool_run_id"],
            ["tool_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tool_run_id", "result_index", name="uq_finding_result"),
    )
    op.create_index(op.f("ix_findings_tool_run_id"), "findings", ["tool_run_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_findings_tool_run_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_tool_runs_scan_id"), table_name="tool_runs")
    op.drop_table("tool_runs")
    op.drop_index(op.f("ix_scans_snapshot_id"), table_name="scans")
    op.drop_table("scans")
    op.drop_index(op.f("ix_source_snapshots_project_id"), table_name="source_snapshots")
    op.drop_table("source_snapshots")
    op.drop_table("projects")
    # ### end Alembic commands ###
